<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://www.axway.com/mappingServices/project" createdBy="didragoescu" lastModifiedBy="didragoescu" checksumTest="true" creationDate="12/05/2015 11:20:14 +0300" engineType="DML" lastModifiedDate="12/05/2015 11:20:27 +0300" engineVersion="2.1">
   <mappingInformations>
      <mappingInformation state="Inactive" path="Mapping Flows/a.dmlflw"/>
   </mappingInformations>
</project>